In [1]:
#task-1
import numpy as np
empty_arr = np.zeros((2,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]]


In [2]:
#task-2
import numpy as np
empty_Arr2=np.ones((4,2))
print(empty_Arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#task-3
array_full=np.full(2,2)
print(array_full)

[2 2]


In [4]:
#task-4
zeros_arr= np.zeros([2,2])
print(zeros_arr)

[[0. 0.]
 [0. 0.]]


In [5]:
#task-5
ones_Arr=np.ones([2,2])
print(ones_Arr)

[[1. 1.]
 [1. 1.]]


In [6]:
#task-6
new_list=[1,2,3,4]
array = np.array(new_list)
print(array)

[1 2 3 4]


In [7]:
#task-1
array_2 = np.arange(10,50)
print(array_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#task-2
array_3 = np.array([0,1,2,3,4,5,6,7,8])
new = array_3.reshape(3,3)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#task-3
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#task-4
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:", random_array)
print("Mean of the array:", mean_value)


Random array: [0.05560235 0.59417213 0.49899302 0.52857144 0.26227136 0.30695762
 0.125894   0.63793307 0.53728608 0.05499148 0.11010885 0.23860716
 0.71573909 0.9616451  0.7361304  0.93685562 0.67768795 0.40705439
 0.65971303 0.2596111  0.91963682 0.42645145 0.4960889  0.47054499
 0.03941358 0.63752857 0.54236067 0.72193995 0.43200261 0.21228304]
Mean of the array: 0.473469194129261


In [11]:
#task-5
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.3346917  0.01347653 0.33891861 0.87450289 0.70492371 0.88733259
  0.63701919 0.19053311 0.74892734 0.64635921]
 [0.75163127 0.3218385  0.60909778 0.87692112 0.5527158  0.04397177
  0.96330279 0.14005965 0.61677427 0.02514544]
 [0.42966435 0.01008376 0.86093304 0.95154458 0.42174631 0.50011608
  0.18655985 0.27439703 0.57968909 0.95625358]
 [0.6153396  0.12917559 0.59211797 0.92748145 0.96728919 0.89245033
  0.33567157 0.22440373 0.42205469 0.01393302]
 [0.4267656  0.44364569 0.20703682 0.54292053 0.49959038 0.92501736
  0.760459   0.65370179 0.18973306 0.68057784]
 [0.3602316  0.04335699 0.69627687 0.21046712 0.71782168 0.00917364
  0.70412682 0.78289184 0.32786377 0.45496741]
 [0.67199932 0.13301128 0.46745441 0.14571865 0.1906503  0.06562351
  0.45948583 0.07897756 0.37851076 0.99382702]
 [0.29963838 0.93408737 0.40609505 0.94202127 0.27867165 0.2190117
  0.60434337 0.89902998 0.88913623 0.10699181]
 [0.6544726  0.08044925 0.08572053 0.16830787 0.39567927 0.52122995

In [12]:
#task-5
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#task-6
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [14]:
#task-7
array_6 = np.array([[1,0,0,0]])
print(array_6)

[[1 0 0 0]]


In [19]:
# prompt: Create a 2d array with 1 on border and 0 inside.

import numpy as np

def create_border_array(rows, cols):


  arr = np.zeros((rows, cols), dtype=int)
  arr[0, :] = 1
  arr[-1, :] = 1
  arr[:, 0] = 1
  arr[:, -1] = 1
  return arr


rows = 3
cols = 3
result_array = create_border_array(rows, cols)
result_array

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [20]:
#Problem 3

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task-1
add = x + y
add2 = w + v
print("Addition1:\n", add)
print("Addition2:\n", add2)

#Task-2

sub = x-y
sub2= w-v
print("Subtraction1:\n", sub)
print("Subtraction2:\n", sub2)


#Task-3
new_x = x*2
new_y = y*3
new_v = v*4
new_w = w*5
print("X:\n", new_x)
print("Y:\n", new_y)
print("V:\n", new_v)
print("Z:\n", new_w)

#Task-4
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
sqrt_v = np.sqrt(v)
sqrt_w = np.sqrt(w)

print("Square root of x:\n", sqrt_x)
print("Square root of y:\n", sqrt_y)
print("Square root of v:\n", sqrt_v)
print("Square root of w:\n", sqrt_w)

#Task-5
dot_v_w=np.dot(v,w)
dot_x_v=np.dot(x,v)
dot_x_y=np.dot(x,y)
print("Dot product of v and w arrays:\n", dot_v_w)
print("Dot product of x and v arrays:\n", dot_x_v)
print("Dot product of x and y arrays:\n", dot_x_y)

#Task-6

array_v_w = np.stack((v, w), axis=0)
print("Stacked v and w arrays:\n", array_v_w)


array_x_y = np.vstack((x, y))
print("Stacked x and y arrays (vertically):\n", array_x_y)

#Task-7
array_x_v=np.vstack((x,v))
print("Stacked x and v arrays (vertically):\n", array_x_v)

Addition1:
 [[ 6  8]
 [10 13]]
Addition2:
 [20 22]
Subtraction1:
 [[-4 -4]
 [-4 -3]]
Subtraction2:
 [2 2]
X:
 [[ 2  4]
 [ 6 10]]
Y:
 [[15 18]
 [21 24]]
V:
 [36 40]
Z:
 [55 60]
Square root of x:
 [[1.         1.41421356]
 [1.73205081 2.23606798]]
Square root of y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Square root of v:
 [3.         3.16227766]
Square root of w:
 [3.31662479 3.46410162]
Dot product of v and w arrays:
 219
Dot product of x and v arrays:
 [29 77]
Dot product of x and y arrays:
 [[19 22]
 [50 58]]
Stacked v and w arrays:
 [[ 9 10]
 [11 12]]
Stacked x and y arrays (vertically):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Stacked x and v arrays (vertically):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [21]:
#Problem 4

#Task-1

import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("A * A_inv = \n", result)
I = np.eye(2)
print("\nIdentity matrix I:\n", I)
print("\nIs A * A_inv approximately equal to I? ", np.allclose(result, I))


#task-2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("\nBA = \n", BA)
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

#task-3
transpose_AB= AB.transpose()
print("(AB)T =\n",transpose_AB)

transpose_B= B.transpose()
transpose_A= A.transpose()
AB_transpose= np.dot(transpose_B,transpose_A)
print("(B)T(A)T =\n",AB_transpose)
print("\nIs (AB)T equal to (B)t(A)t? ", np.array_equal(transpose_AB, AB_transpose))





A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
 [[1. 0.]
 [0. 1.]]

Is A * A_inv approximately equal to I?  True
AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

Is AB equal to BA?  False
(AB)T =
 [[23 51]
 [13 29]]
(B)T(A)T =
 [[23 51]
 [13 29]]

Is (AB)T equal to (B)t(A)t?  True


In [25]:

import time
import numpy as np


size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start_time_list = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list

print(f"Time taken for element-wise addition using Python lists: {end_time_list - start_time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
result_array = array1 + array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy

print(f"Time taken for element-wise addition using NumPy arrays: {end_time_numpy - start_time_numpy:.6f} seconds")




Time taken for element-wise addition using Python lists: 0.168589 seconds
Time taken for element-wise addition using NumPy arrays: 0.002513 seconds


In [24]:
import time
import numpy as np
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start_time_list = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for element-wise multiplication using Python lists: {time_list:.6f} seconds")
array1 = np.arange(size)
array2 = np.arange(size)
start_time_numpy = time.time()
result_array = array1 * array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken for element-wise multiplication using NumPy arrays: {time_numpy:.6f} seconds")

Time taken for element-wise multiplication using Python lists: 0.329253 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.005230 seconds


In [26]:
import time
import numpy as np

size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time_list = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for dot product using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time_numpy = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken for dot product using NumPy arrays: {time_numpy:.6f} seconds")

Time taken for dot product using Python lists: 0.321976 seconds
Time taken for dot product using NumPy arrays: 0.002238 seconds


In [ ]:
import time
import numpy as np

size = 1000
matrix1 = [[i for i in range(size)] for _ in range(size)]
matrix2 = [[i for i in range(size)] for _ in range(size)]

start_time_list = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken for matrix multiplication using Python lists: {time_list:.6f} seconds")

array1 = np.arange(size * size).reshape(size, size)
array2 = np.arange(size * size).reshape(size, size)

start_time_numpy = time.time()
result_array = np.dot(array1, array2)
end_time_numpy = time.time()

print(f"Time taken for matrix multiplication using NumPy arrays: {time_numpy:.6f} seconds")

